name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: |
        docker build . -t rekrutacja:latest
    - name: Run Image
      run: |
        docker image ls
        docker run -d -p 0.0.0.0:80:80 --name rekrutacja rekrutacja:latest 
    - name: Test Image
      run: |
        curl -L http://127.0.0.1:80/angular-hello-world
    - name: Test Compose
      run: |
        ruby create_compose.rb -c rekrutacja_2 -i rekrutacja -t latest -p 8080:80
        docker compose up -d
        docker ps
        curl -L http://127.0.0.1:8080/angular-hello-world
      
