name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: |
        docker build . -t rekrutacja:latest
    - name: Run Image
      run: |
        docker run -d -p 0.0.0.0:80:80 --name rekrutacja rekrutacja:latest 
    - name: Test Image
      run: |
        curl -L http://127.0.0.1:80/angular-hello-world
    - name: Build and Test Compose
      run: |
        ruby create_compose.rb --container-name "rekrutacja_2" --image-name "rekrutacja" --image-tag "latest" --ports "8080:80"
        cat compose.yaml
        docker compose up -d
        docker ps
        curl -L http://127.0.0.1:8080/angular-hello-world
      
